# Use the Nginx image as a base
FROM nginx:latest

# Set up Nginx configuration to redirect to Taler Wallet page
RUN echo 'server {
    listen 80;
    location / {
        return 301 https://taler.net/fr/wallet.html;
    }
}' > /etc/nginx/conf.d/default.conf

# Expose port 80 for web access
EXPOSE 80
